"""Add enable_silent_push_notifications to vehicles table

Revision ID: 0c1a876091f8
Revises: 756aafc64c77
Create Date: 2025-10-10 00:12:12.163189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1a876091f8'
down_revision: Union[str, None] = '756aafc64c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('enable_silent_push_notifications', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'enable_silent_push_notifications')
    # ### end Alembic commands ###
