"""create_initial_tables

Revision ID: 61cac9330735
Revises: 
Create Date: 2025-05-23 16:18:58.812905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61cac9330735'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=32), nullable=False),
    sa.Column('vehicle_name', sa.String(length=100), nullable=True),
    sa.Column('encrypted_server_password', sa.LargeBinary(), nullable=False),
    sa.Column('encrypted_module_password', sa.LargeBinary(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('latest_status_msg', sa.Text(), nullable=True),
    sa.Column('latest_location_msg', sa.Text(), nullable=True),
    sa.Column('latest_diag_msg', sa.Text(), nullable=True),
    sa.Column('latest_firmware_msg', sa.Text(), nullable=True),
    sa.Column('latest_tpms_w_msg', sa.Text(), nullable=True),
    sa.Column('latest_tpms_y_msg', sa.Text(), nullable=True),
    sa.Column('paranoid_token', sa.String(length=64), nullable=True),
    sa.Column('enable_ntfy_notifications', sa.Boolean(), nullable=True),
    sa.Column('enable_email_notifications', sa.Boolean(), nullable=True),
    sa.Column('enable_fcm_notifications', sa.Boolean(), nullable=True),
    sa.Column('ntfy_topic', sa.String(length=100), nullable=True),
    sa.Column('ntfy_server_url', sa.String(length=255), nullable=True),
    sa.Column('ntfy_auth_method', sa.String(length=50), nullable=True),
    sa.Column('ntfy_auth_token', sa.String(length=255), nullable=True),
    sa.Column('ntfy_auth_user', sa.String(length=100), nullable=True),
    sa.Column('ntfy_auth_password', sa.String(length=100), nullable=True),
    sa.Column('ntfy_auth_query_param_name', sa.String(length=50), nullable=True),
    sa.Column('notification_email', sa.String(length=255), nullable=True),
    sa.Column('fcm_token', sa.String(length=255), nullable=True),
    sa.Column('apns_token', sa.String(length=255), nullable=True),
    sa.Column('last_seen_tcp', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_vehicle_owner_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_last_message_at'), 'vehicles', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_vehicles_last_seen_tcp'), 'vehicles', ['last_seen_tcp'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_id'), 'vehicles', ['vehicle_id'], unique=True)
    op.create_index(op.f('ix_vehicles_vehicle_name'), 'vehicles', ['vehicle_name'], unique=False)
    op.create_table('auto_provision_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ap_key', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('target_vehicle_id_str', sa.String(length=32), nullable=False),
    sa.Column('target_server_password', sa.String(length=32), nullable=False),
    sa.Column('target_vehicle_name', sa.String(length=100), nullable=True),
    sa.Column('target_module_password', sa.String(length=32), nullable=True),
    sa.Column('encrypted_module_params_b64', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('vehicle_id_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_autoprovision_owner_id'),
    sa.ForeignKeyConstraint(['vehicle_id_fk'], ['vehicles.id'], name='fk_autoprovision_target_vehicle_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_vehicle_id_str'),
    sa.UniqueConstraint('vehicle_id_fk')
    )
    op.create_index(op.f('ix_auto_provision_profiles_ap_key'), 'auto_provision_profiles', ['ap_key'], unique=True)
    op.create_index(op.f('ix_auto_provision_profiles_id'), 'auto_provision_profiles', ['id'], unique=False)
    op.create_table('historical_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id_fk', sa.Integer(), nullable=False),
    sa.Column('vehicle_module_id_str', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('message_code', sa.String(length=1), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=True),
    sa.Column('record_number', sa.Integer(), nullable=True),
    sa.Column('data_payload', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id_fk'], ['vehicles.id'], name='fk_historicaldata_vehicle_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_data_expires_at'), 'historical_data', ['expires_at'], unique=False)
    op.create_index(op.f('ix_historical_data_id'), 'historical_data', ['id'], unique=False)
    op.create_index(op.f('ix_historical_data_timestamp'), 'historical_data', ['timestamp'], unique=False)
    op.create_index('ix_historical_data_vehicle_fk_timestamp', 'historical_data', ['vehicle_id_fk', 'timestamp'], unique=False)
    op.create_index(op.f('ix_historical_data_vehicle_module_id_str'), 'historical_data', ['vehicle_module_id_str'], unique=False)
    op.create_index('ix_historical_data_vehicle_rectype_recnum_time', 'historical_data', ['vehicle_id_fk', 'record_type', 'record_number', 'timestamp'], unique=True, sqlite_where=sa.text('record_type IS NOT NULL AND record_number IS NOT NULL'))
    op.create_index('ix_historical_data_vehicle_str_id_timestamp', 'historical_data', ['vehicle_module_id_str', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_historical_data_vehicle_str_id_timestamp', table_name='historical_data')
    op.drop_index('ix_historical_data_vehicle_rectype_recnum_time', table_name='historical_data', sqlite_where=sa.text('record_type IS NOT NULL AND record_number IS NOT NULL'))
    op.drop_index(op.f('ix_historical_data_vehicle_module_id_str'), table_name='historical_data')
    op.drop_index('ix_historical_data_vehicle_fk_timestamp', table_name='historical_data')
    op.drop_index(op.f('ix_historical_data_timestamp'), table_name='historical_data')
    op.drop_index(op.f('ix_historical_data_id'), table_name='historical_data')
    op.drop_index(op.f('ix_historical_data_expires_at'), table_name='historical_data')
    op.drop_table('historical_data')
    op.drop_index(op.f('ix_auto_provision_profiles_id'), table_name='auto_provision_profiles')
    op.drop_index(op.f('ix_auto_provision_profiles_ap_key'), table_name='auto_provision_profiles')
    op.drop_table('auto_provision_profiles')
    op.drop_index(op.f('ix_vehicles_vehicle_name'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_vehicle_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_last_seen_tcp'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_last_message_at'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###