"""add_last_seen_v3_to_vehicle

Revision ID: 9b8c7d6e5f4a
Revises: 8a1b2c3d4e5f
Create Date: 2025-05-29 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8c7d6e5f4a'
down_revision: Union[str, None] = '8a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_v3', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_vehicles_last_seen_v3'), ['last_seen_v3'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_last_seen_v3'))
        batch_op.drop_column('last_seen_v3')

    # ### end Alembic commands ###