"""Add charge logging feature

Revision ID: a0b1c2d3e4f5
Revises: j1k2l3m4n5o6
Create Date: 2025-09-29 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID


# revision identifiers, used by Alembic.
revision: str = 'a0b1c2d3e4f5'
down_revision: Union[str, None] = 'j1k2l3m4n5o6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    dialect = op.get_context().dialect.name
    uuid_type = PG_UUID(as_uuid=True) if dialect == 'postgresql' else sa.String(36)

    op.create_table('charge_logs',
        sa.Column('id', uuid_type, nullable=False),
        sa.Column('vehicle_id_fk', sa.Integer(), nullable=False),
        sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
        sa.Column('start_soc', sa.Float(), nullable=True),
        sa.Column('end_soc', sa.Float(), nullable=True),
        sa.Column('energy_added_kwh', sa.Float(), nullable=True),
        sa.Column('max_power_kw', sa.Float(), nullable=True),
        sa.Column('average_power_kw', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['vehicle_id_fk'], ['vehicles.id'], name=op.f('fk_charge_logs_vehicle_id_fk_vehicles'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_logs_id'), 'charge_logs', ['id'], unique=False)
    op.create_index(op.f('ix_charge_logs_start_time'), 'charge_logs', ['start_time'], unique=False)
    op.create_index(op.f('ix_charge_logs_vehicle_id_fk'), 'charge_logs', ['vehicle_id_fk'], unique=False)
    
    op.create_table('charge_log_points',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('charge_log_id_fk', uuid_type, nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('soc', sa.Float(), nullable=True),
        sa.Column('power_kw', sa.Float(), nullable=True),
        sa.Column('battery_temp_c', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['charge_log_id_fk'], ['charge_logs.id'], name=op.f('fk_charge_log_points_charge_log_id_fk_charge_logs'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_log_points_charge_log_id_fk'), 'charge_log_points', ['charge_log_id_fk'], unique=False)
    op.create_index(op.f('ix_charge_log_points_id'), 'charge_log_points', ['id'], unique=False)
    op.create_index(op.f('ix_charge_log_points_timestamp'), 'charge_log_points', ['timestamp'], unique=False)
    
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_charge_logging', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('enable_charge_logging')

    op.drop_index(op.f('ix_charge_log_points_timestamp'), table_name='charge_log_points')
    op.drop_index(op.f('ix_charge_log_points_id'), table_name='charge_log_points')
    op.drop_index(op.f('ix_charge_log_points_charge_log_id_fk'), table_name='charge_log_points')
    op.drop_table('charge_log_points')
    
    op.drop_index(op.f('ix_charge_logs_vehicle_id_fk'), table_name='charge_logs')
    op.drop_index(op.f('ix_charge_logs_start_time'), table_name='charge_logs')
    op.drop_index(op.f('ix_charge_logs_id'), table_name='charge_logs')
    op.drop_table('charge_logs')
    # ### end Alembic commands ###