"""add_historical_data_lookup_index

Revision ID: c1a2b3d4e5f6
Revises: a1b2c3d4e5f6
Create Date: 2025-05-31 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a2b3d4e5f6'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_historical_data_vehicle_str_rectype_time', 'historical_data', ['vehicle_module_id_str', 'record_type', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_historical_data_vehicle_str_rectype_time', table_name='historical_data')
    # ### end Alembic commands ###