"""Add email verification to user

Revision ID: e9c1d2b3a4f5
Revises: 2fdbcc1a8b3c
Create Date: 2025-05-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c1d2b3a4f5'
down_revision: Union[str, None] = '2fdbcc1a8b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # For databases that don't support altering column nullability easily (like SQLite),
        # this might require a table recreation sequence. For PostgreSQL/MySQL, this is fine.
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_email_verification_token'), ['email_verification_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email_verification_token'))
        batch_op.drop_column('email_verification_token_expires_at')
        batch_op.drop_column('email_verification_token')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###