"""refactor historical_data table

Revision ID: g2h3i4j5k6l7
Revises: f0e1d2c3b4a5
Create Date: 2025-07-16 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'g2h3i4j5k6l7'
down_revision: Union[str, None] = 'f0e1d2c3b4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_data', schema=None) as batch_op:
        # Step 1: Make record_type non-nullable. 
        # The application logic ensured that this column was always populated based on message_code,
        # so it's safe to enforce this constraint without data loss.
        batch_op.alter_column('record_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
               
        # Step 2: Drop the redundant message_code column.
        batch_op.drop_column('message_code')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_data', schema=None) as batch_op:
        # Step 1: Re-add the message_code column, allowing nulls for now.
        batch_op.add_column(sa.Column('message_code', sa.VARCHAR(length=1), nullable=True))

    # Step 2: Populate the new message_code column based on the record_type.
    # If record_type is longer than 1 char (like 'Crash'), it was an 'H' message.
    # Otherwise, the message_code was the same as the record_type.
    op.execute("UPDATE historical_data SET message_code = CASE WHEN LENGTH(record_type) > 1 THEN 'H' ELSE record_type END")

    with op.batch_alter_table('historical_data', schema=None) as batch_op:
        # Step 3: Now that the column is populated, make it non-nullable.
        batch_op.alter_column('message_code',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
               
        # Step 4: Make record_type nullable again, as it was before.
        batch_op.alter_column('record_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###