"""Add position and odometer to charge logs

Revision ID: m9n0o1p2q3r4
Revises: l8m9n0o1p2q3
Create Date: 2025-11-03 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'm9n0o1p2q3r4'
down_revision: Union[str, None] = 'l8m9n0o1p2q3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charge_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('start_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('start_odometer', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charge_logs', schema=None) as batch_op:
        batch_op.drop_column('start_odometer')
        batch_op.drop_column('start_longitude')
        batch_op.drop_column('start_latitude')

    # ### end Alembic commands ###
